version: "3.8"

services:
    backend:
        build:
            context: ./phpConf
            dockerfile: Dockerfile
        restart: always
        ports:
            - "1320:80"
        volumes:
            - ./app:/var/www/html

    database:
        image: mariadb
        restart: always
        volumes:
            - ./database/dump.sql:/docker-entrypoint-initdb.d/dump.sql
        environment:
            MYSQL_DATABASE: glad_blog
            MYSQL_ROOT_PASSWORD: password

    adminer:
        image: adminer
        ports:
            -  "1301:8080"

    frontend:
        build:
            context: ./reactConf
            dockerfile: Dockerfile
        ports:
            - "3000:3000"
        volumes:
            - ./frontend:/project

volumes:
    db_glad_blog: